"""Add client, network, and client_network tables

Revision ID: 13eb6d4206b1
Revises:
Create Date: 2025-06-07 12:02:00.498199

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "13eb6d4206b1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "network",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ipv4", sa.String(length=18), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ipv4"),
    )
    op.create_table(
        "client_network",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("network_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["network.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "network_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doc_sections",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("doc_sections_pkey")),
        sa.UniqueConstraint(
            "url",
            name=op.f("doc_sections_url_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_doc_sections_embedding"),
        "doc_sections",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
    )
    op.drop_table("client_network")
    op.drop_table("network")
    op.drop_table("client")
    # ### end Alembic commands ###
