name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          uv sync

      - name: Start PostgreSQL with Docker Compose
        run: |
          uv run docker compose up -d

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5435/postgres
        run: uv run pytest